# Travis CI config file
# https://docs.travis-ci.com/

dist: xenial

language: node_js

node_js:
  - "13.*"
  - "12.*"
  - "11.*"
  - "10.*"
  - "9.*"
  - "8.*"

cache:
  yarn: true

before_install:
  - sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
  - yarn global add node-gyp

install:
  - yarn --ignore-engines # AVA is not officially supported on Node.js 9.x

before_script:
  - yarn build

script:
  - node test/_node-version-test.js
  - yarn test
